<a href="https://colab.research.google.com/github/ggwnsghgg/FastCampus/blob/main/2021_2_9_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
# reshape 코드입력
from sklearn.linear_model import LinearRegression

In [2]:
x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

In [3]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## 모델의 선언, fit(학습), predict(예측)

In [5]:
# 모델 선언
model = LinearRegression()

In [6]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
# 학습
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
# 예측
prediction = model.predict([[10]])

In [11]:
prediction

array([[21.]])