<a href="https://colab.research.google.com/github/ggwnsghgg/FastCampus/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip list

Package                       Version       
----------------------------- --------------
absl-py                       0.10.0        
alabaster                     0.7.12        
albumentations                0.1.12        
altair                        4.1.0         
appdirs                       1.4.4         
argon2-cffi                   20.1.0        
asgiref                       3.3.1         
astor                         0.8.1         
astropy                       4.2           
astunparse                    1.6.3         
async-generator               1.10          
atari-py                      0.2.6         
atomicwrites                  1.4.0         
attrs                         20.3.0        
audioread                     2.1.9         
autograd                      1.3           
Babel                         2.9.0         
backcall                      0.2.0         
beautifulsoup4                4.6.3         
bleach                        3.3.0         
blis      


##Pytorch Basics
- Stevens, Antiga and Viehmann (2020), "Deep Learning with PyTorch" 참고
- PyTorch tutorial website 참고(https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html)
##PyTorch
-provides multidimensional arrays
- tensors, and an extensive library of operations on them

In [3]:
# torch가 설치되어 있지 않다면
# https://pytorch.org 에서 환경에 맞는 command로 설치하거나
# !pip install torch
# 또는 !pip3 install torch (Python3 환경임을 명시)

import torch


# 1. Tensor란? Tensor 만들기
- Tensors: Multidimensional arrays

In [4]:
# Create a torch.Tensor object with the given data.  It is a 1D vector
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1.,2.], [3.,4.]],
          [[5.,6.], [7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [5]:
# torch.ones: tensor를 size에 맞게 1로 채운다
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# torch.zeros: tensor를 size에 맞게 0으로 채운다
c = torch.zeros(4)
print(c)

d = torch.zeros(5, 2, 3)
print(d)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

tensor([[1.9045e-22, 3.0928e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])
tensor([[0.9888, 0.0764, 0.7371],
        [0.8579, 0.4440, 0.8651],
        [0.2642, 0.9069, 0.2739],
        [0.3667, 0.8247, 0.1581],
        [0.0096, 0.5804, 0.2070]])


In [8]:
# torch.rand: 랜덤 숫자로 tensor를 채운다
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2, 3, dtype=torch.float)
print(rand_points_2)

tensor([0.9045, 0.5214, 0.6733, 0.1879], dtype=torch.float64)
tensor([[0.6418, 0.4700, 0.9388],
        [0.2220, 0.5901, 0.1236]])


In [9]:
# 행렬 사이즈
print(rand_points_2.size())

torch.Size([2, 3])


In [10]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # index 1과 4 사이의 원소들 출력
print(temp[1:]) # index 1부터의 원소들 출력
print(temp[:4]) # index 4까지의 원소들 출력
print(temp[-1]) # 뒤에서 첫번째 원소 출력
print(temp[:-1]) # index -1 = 뒤에서부터 index 1에 해당하는 원소까지만 출력
print(temp[1:6:2]) # index 1과 6 사이의 원소 출력, 이때 2개 단위로 건너뛰면서

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3.])
tensor(7.)
tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([1., 3., 5.])


In [11]:
temp2 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(temp2)
print(temp2[1:])
print(temp2[1:, 1:])
print(temp2[1:, 0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4., 5., 6.]])
tensor([[5., 6.]])
tensor([4.])



3. Tensor element types
add 'dtype' argument to tensor constructors

-> specify the data type that will be contained in the tensor

dtype을 구성하는 것:

possible values the tensor can hold (int, float, ...)
number of bytes per value (8, 16, 32, ...)
예)

torch.float32 (= torch.float): 32-bit floating point

torch.float64 (= torch.double): 64-bit, double-precision floating point

torch.float16 (= torch.half): 16-bit, half-precision floating point

torch.int32 (= torch.int): 32-bit integers

torch.int64 (= torch.long): 64-bit integers

torch.bool: Boolean

In [12]:
float_points = torch.ones(5, 2, dtype=torch.float32)
int_points = torch.zeros(3, dtype=torch.int64)

print(float_points)
print(int_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [13]:
# default: float
default_points = torch.Tensor([2, 2])
print(default_points)

tensor([2., 2.])


In [14]:
# find out dtype
print(float_points.dtype)
print(int_points.dtype)
print(default_points.dtype)

torch.float32
torch.int64
torch.float32


In [15]:
# other forms of specifying dtype

to_int_1 = float_points.int()
print(to_int_1.dtype)

# 'to' checks whether the conversion is necessary and if so, does it.
to_int_2 = float_points.to(torch.int64)
print(to_int_2.dtype)

to_float_1 = int_points.float()
print(to_float_1.dtype)

to_float_2 = int_points.to(dtype=torch.float16)
print(to_float_2.dtype)

torch.int32
torch.int64
torch.float32
torch.float16



# 4. The Tensor API
tensor와 관련된 대부분의 operation은 torch 모듈에 구현되어 있음

예)

- math operations: abs, cos, mean, std, norm, equal, max, ...
- tensor element-wise sum, concat, ...
- random sampling: randn, normal, ...
online docs: https://pytorch.org/docs

# 5. Tensor Shape and Reshape

In [16]:

# shape: Returns the size of the tensor

a = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(a)
print(a.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [17]:
# size()

print(a.size())

torch.Size([2, 3])


In [18]:
# Reshape: 주어진 shape로 original tensor에서 데이터를 가져와서 reshape한다

a_reshape = a.reshape(3, 2)
print(a_reshape)
print(a_reshape.shape)

a_reshape_2 = a.reshape(-1, 2) # the size -1 is inferred from other dimensions
print(a_reshape_2)
print(a_reshape_2.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [19]:
# if shape is not compatible with the current shape:
a_no_reshape = a.reshape(4, 2) # index 값 부족 if shape is not compatible with the current shape:
a_no_reshape = a.reshape(4, 2) # index 값 부족



RuntimeError: ignored

In [20]:

# View: Returns a new tensor with the same data as the original tensor but of a different shape.
# reshape과 거의 비슷하게 사용

x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [21]:
print(x)

print()
print("--------")
print()

print(y)

print()
print("--------")
print()

print(z)

tensor([[ 0.8478, -0.4487, -1.5874,  1.1287],
        [-0.0567, -3.0185, -1.9602,  1.9079],
        [ 1.9861, -0.9342,  1.1133,  0.5008],
        [ 0.7589, -1.5726, -0.4976,  0.2565]])

--------

tensor([ 0.8478, -0.4487, -1.5874,  1.1287, -0.0567, -3.0185, -1.9602,  1.9079,
         1.9861, -0.9342,  1.1133,  0.5008,  0.7589, -1.5726, -0.4976,  0.2565])

--------

tensor([[ 0.8478, -0.4487, -1.5874,  1.1287, -0.0567, -3.0185, -1.9602,  1.9079],
        [ 1.9861, -0.9342,  1.1133,  0.5008,  0.7589, -1.5726, -0.4976,  0.2565]])


In [22]:
# torch.t: 가장 간단한 형태의 transpose
# Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.
# 0-D and 1-D tensors are returned as is. When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).

x = torch.randn(1)
print(x)
print(torch.t(x))

y = torch.randn(3)
print(y)x   
print(y.t())

z = torch.randn(2, 3)
print(z)
print(torch.t(z))

SyntaxError: ignored

In [23]:
# torch.transpose
# Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

w = torch.randn(2, 3)
print(w)
print(torch.transpose(w, 0, 1))

tensor([[ 1.3592,  0.4821,  1.6673],
        [-0.1554,  0.9784,  0.7799]])
tensor([[ 1.3592, -0.1554],
        [ 0.4821,  0.9784],
        [ 1.6673,  0.7799]])


In [24]:
# more complex case

real_example = torch.randn(64, 128, 768)
print(real_example.shape)
transposed = torch.transpose(real_example, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


In [25]:
# more complex case

real_example = torch.randn(64, 128, 768)
print(real_example.shape)
transposed = torch.transpose(real_example, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


In [26]:
x = torch.ones(1, 2)
print(x)
y = torch.ones(5, 3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [27]:
print(x+y)

RuntimeError: ignored

In [29]:

y = torch.ones(5, 2)
print(y)

# 1.
print(x+y)
# 2. 
print(torch.add(x, y))
# 3.
result = torch.empty(5, 2)
torch.add(x, y, out=result)
print(result)
# 4. inplace
print(y.add_(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])



## Additional Information
- torch 연산(transpose, indexing, slicing, mathematical operations, linear algebra 등)은 아래 링크에서 추가로 확인 가능
- https://pytorch.org/docs/stable/torch.html
## Reference: Moving tensors to the GPU
if you are using Google Colaboratory, please set the runtime type to GPUs.

화면 상단 런타임 >> 런타임 유형 변경 >> 하드웨어 가속기 GPU 선택

In [28]:
torch.cuda.is_available()

True

In [30]:
import torch # 런타임 유형을 변경하면 colab 세션이 초기화될 수 있음

points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [31]:
points = torch.randn(2, 3)
points_gpu = points.to(device='cuda')

print(points_gpu)

tensor([[0.0498, 0.3454, 0.6121],
        [1.6089, 0.3407, 1.2919]], device='cuda:0')


In [32]:
points_gpu_0 = points.to(device='cuda:0')
print(points_gpu_0)

tensor([[0.0498, 0.3454, 0.6121],
        [1.6089, 0.3407, 1.2919]], device='cuda:0')


In [33]:
# operations performed on CPU and GPU

points = 2 * points   # cpu에서 계산 수행
print(points)

points_op_gpu = 2 * points.to(device='cuda')  # gpu에서 계산 수행
print(points_op_gpu)

tensor([[0.0997, 0.6908, 1.2242],
        [3.2177, 0.6815, 2.5839]])
tensor([[0.1993, 1.3817, 2.4483],
        [6.4355, 1.3630, 5.1677]], device='cuda:0')


In [34]:

# move the tensor back to the CPU

points_cpu = points_gpu_0.to(device='cpu')
print(points_cpu)
print(points_cpu.device)

tensor([[0.0498, 0.3454, 0.6121],
        [1.6089, 0.3407, 1.2919]])
cpu


In [35]:
# shorter forms
points_gpu = points.cuda()
print(points_gpu)

points_gpu = points.cuda(0)
print(points_gpu)

points_cpu = points_gpu.cpu()
print(points_cpu)

tensor([[0.0997, 0.6908, 1.2242],
        [3.2177, 0.6815, 2.5839]], device='cuda:0')
tensor([[0.0997, 0.6908, 1.2242],
        [3.2177, 0.6815, 2.5839]], device='cuda:0')
tensor([[0.0997, 0.6908, 1.2242],
        [3.2177, 0.6815, 2.5839]])


In [36]:
# tensor to numpy array

points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:

points = torch.from_numpy(points_np)

print(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



## 파일저장

In [38]:
print(points)

torch.save(points, './points_temp.t')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [39]:
load_points = torch.load('./points_temp.t')
print(load_points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
