<a href="https://colab.research.google.com/github/ggwnsghgg/FastCampus/blob/main/%EA%B8%B0%EB%B3%B8%EC%BD%94%EB%93%9C%ED%9B%88%EB%A0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## 1. numpy, array, matrix 등

In [ ]:
import warnings
import numpy as np
warnings.filterwarnings("ignore")

### 리스트, 행렬 선언

In [ ]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [ ]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [ ]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [ ]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((1, 5)))
print(np.ones((3, 2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5)))
print(np.zeros((3, 2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:

# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [ ]:

# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[7 5]
 [2 6]
 [3 2]]
[[0.42977376 0.86688713]
 [0.18013564 0.20180578]
 [0.93822092 0.00121369]]


**리스트 인덱싱(Indexing) & 슬라이싱(Slicing**

In [ ]:

# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [ ]:
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


**numpy의 reshape (PyTorch의 view와 비교)**

In [ ]:

# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.40680711 0.04011088 0.84519065]
 [0.94820812 0.00683675 0.64851462]
 [0.13812171 0.68633103 0.9662075 ]
 [0.33189112 0.28300442 0.21025054]
 [0.08644741 0.90565945 0.30258431]
 [0.2649564  0.36360641 0.71147608]]


In [ ]:
# -1: all
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

(1, 18)
[[0.65479073 0.02701063 0.30966554 0.89387263 0.62398145 0.61924527
  0.35119917 0.14728155 0.97152659 0.48591906 0.20931785 0.46945018
  0.70136112 0.49407847 0.85682403 0.72470492 0.03107278 0.62194844]]
=====
(18, 1)
[[0.65479073]
 [0.02701063]
 [0.30966554]
 [0.89387263]
 [0.62398145]
 [0.61924527]
 [0.35119917]
 [0.14728155]
 [0.97152659]
 [0.48591906]
 [0.20931785]
 [0.46945018]
 [0.70136112]
 [0.49407847]
 [0.85682403]
 [0.72470492]
 [0.03107278]
 [0.62194844]]


In [ ]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.65479073 0.02701063]
 [0.30966554 0.89387263]
 [0.62398145 0.61924527]
 [0.35119917 0.14728155]
 [0.97152659 0.48591906]
 [0.20931785 0.46945018]
 [0.70136112 0.49407847]
 [0.85682403 0.72470492]
 [0.03107278 0.62194844]]


In [ ]:
mat1.reshape(2,5)

ValueError: ignored

In [ ]:
# tensor 형태로 나타내기 tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.40680711 0.04011088 0.84519065]
  [0.94820812 0.00683675 0.64851462]]

 [[0.13812171 0.68633103 0.9662075 ]
  [0.33189112 0.28300442 0.21025054]]

 [[0.08644741 0.90565945 0.30258431]
  [0.2649564  0.36360641 0.71147608]]]


In [ ]:

mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
mat2[:1,:3]

array([[0, 1, 2]])

In [ ]:
mat2[3, 0:2]

array([12, 13])

In [ ]:

x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:

# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [ ]:
x-y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
x*y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [ ]:
x/y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [ ]:
print(x ** 2)
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [ ]:
np.dot(x, y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [ ]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [ ]:

# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [ ]:
print(z2.shape)
print(x.shape)
print(x * z2)

(1, 2)
(3, 3)


ValueError: ignored

In [ ]:

# 합
print(x)
print(x.sum(axis = 0))
print(x.sum(axis = 1))

In [ ]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))