<a href="https://colab.research.google.com/github/ggwnsghgg/FastCampus/blob/main/%EA%B8%B0%EB%B3%B8%EC%BD%94%EB%93%9C%ED%9B%88%EB%A0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## 1. numpy, array, matrix 등

In [1]:
import warnings
import numpy as np
warnings.filterwarnings("ignore")

### 리스트, 행렬 선언

In [2]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [3]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [4]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [5]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((1, 5)))
print(np.ones((3, 2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5)))
print(np.zeros((3, 2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:

# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [8]:

# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[2 6]
 [3 2]
 [6 1]]
[[0.73563328 0.83364813]
 [0.73382594 0.92454581]
 [0.71599532 0.08346526]]


**리스트 인덱싱(Indexing) & 슬라이싱(Slicing**

In [9]:

# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [10]:
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


**numpy의 reshape (PyTorch의 view와 비교)**

In [11]:

# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.38124279 0.44011135 0.69044744]
 [0.40971698 0.89258147 0.74748966]
 [0.65841525 0.38909539 0.32866993]
 [0.29324172 0.39736411 0.67825066]
 [0.82639172 0.36342221 0.5467123 ]
 [0.03693886 0.55667174 0.74668394]]


In [12]:
# -1: all
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

(1, 18)
[[0.38124279 0.44011135 0.69044744 0.40971698 0.89258147 0.74748966
  0.65841525 0.38909539 0.32866993 0.29324172 0.39736411 0.67825066
  0.82639172 0.36342221 0.5467123  0.03693886 0.55667174 0.74668394]]
=====
(18, 1)
[[0.38124279]
 [0.44011135]
 [0.69044744]
 [0.40971698]
 [0.89258147]
 [0.74748966]
 [0.65841525]
 [0.38909539]
 [0.32866993]
 [0.29324172]
 [0.39736411]
 [0.67825066]
 [0.82639172]
 [0.36342221]
 [0.5467123 ]
 [0.03693886]
 [0.55667174]
 [0.74668394]]


In [13]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.38124279 0.44011135]
 [0.69044744 0.40971698]
 [0.89258147 0.74748966]
 [0.65841525 0.38909539]
 [0.32866993 0.29324172]
 [0.39736411 0.67825066]
 [0.82639172 0.36342221]
 [0.5467123  0.03693886]
 [0.55667174 0.74668394]]


In [14]:
mat1.reshape(2,5)

ValueError: ignored

In [15]:
# tensor 형태로 나타내기 tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.38124279 0.44011135 0.69044744]
  [0.40971698 0.89258147 0.74748966]]

 [[0.65841525 0.38909539 0.32866993]
  [0.29324172 0.39736411 0.67825066]]

 [[0.82639172 0.36342221 0.5467123 ]
  [0.03693886 0.55667174 0.74668394]]]
(3, 2, 3)
[[[0.38124279 0.44011135 0.69044744]
  [0.40971698 0.89258147 0.74748966]]

 [[0.65841525 0.38909539 0.32866993]
  [0.29324172 0.39736411 0.67825066]]

 [[0.82639172 0.36342221 0.5467123 ]
  [0.03693886 0.55667174 0.74668394]]]


In [16]:

mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
mat2[:1,:3]

array([[0, 1, 2]])

In [18]:
mat2[3, 0:2]

array([12, 13])

In [19]:

x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [20]:

# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [21]:
x-y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [22]:
x*y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [23]:
x/y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [24]:
print(x ** 2)
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [25]:
np.dot(x, y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [26]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [27]:

# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [28]:
print(z2.shape)
print(x.shape)
print(x * z2)

(1, 2)
(3, 3)


ValueError: ignored

In [29]:

# 합
print(x)
print(x.sum(axis = 0))
print(x.sum(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [30]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [32]:
# 표준표차
print(x)
print(x.mean(axis=0))
print(x.mean(axis=1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [33]:
# 표준표차
print(x)
print(x.std(axis=0))
print(x.std(axis=1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[4.89897949 4.89897949 4.89897949]
[1.63299316 1.63299316 1.63299316]


In [35]:
# 표준표차
print(x.T)
print(z1)
print(np.dot(x, z1.T))


[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
[[2 2 2]]
[[18]
 [54]
 [90]]


In [36]:
xx = np.random.rand(15)
print(xx)

[9.17444728e-01 6.33898870e-01 1.36767445e-01 2.17104251e-01
 3.71224482e-01 8.88192702e-01 3.57728873e-01 1.26071293e-02
 4.85974574e-01 1.35375623e-01 7.79762665e-01 9.38418114e-02
 3.56762803e-01 4.96141659e-01 2.87338269e-04]


In [37]:
print(xx)
print(xx.argsort())
xx.sort
print(xx)

[9.17444728e-01 6.33898870e-01 1.36767445e-01 2.17104251e-01
 3.71224482e-01 8.88192702e-01 3.57728873e-01 1.26071293e-02
 4.85974574e-01 1.35375623e-01 7.79762665e-01 9.38418114e-02
 3.56762803e-01 4.96141659e-01 2.87338269e-04]
[14  7 11  9  2  3 12  6  4  8 13  1 10  5  0]
[9.17444728e-01 6.33898870e-01 1.36767445e-01 2.17104251e-01
 3.71224482e-01 8.88192702e-01 3.57728873e-01 1.26071293e-02
 4.85974574e-01 1.35375623e-01 7.79762665e-01 9.38418114e-02
 3.56762803e-01 4.96141659e-01 2.87338269e-04]


In [38]:
import pandas as pd

In [41]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data=[1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [42]:
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [43]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_series.loc['a'])
print(pd_series.iloc[0])

print(pd_series.loc[['a','c']])
print(pd_series.iloc[[0,2]])

1
1
a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


In [44]:
pd_series.drop('b')

a    1
c    3
d    4
e    5
dtype: int64

In [45]:
print(pd_series)
pd_series.drop('b', inplace=True)
print(pd_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


In [46]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [55]:
data_df

A   B         C
0    0  13  0.247145
1    1  10  0.890317
2    2   1  0.635175
3    3  13  0.360963
4    4   9  0.803401
5    5  10  0.371818
6    6   2  0.985415
7    7  14  0.758669
8    8   2  0.807335
9    9   7  0.882133
10  10   7  0.255349
11  11  11  0.758977
12  12   3  0.294407
13  13   0  0.454479
14  14   6  0.284229

In [47]:
data_df.tail()

A   B         C
10  10   7  0.255349
11  11  11  0.758977
12  12   3  0.294407
13  13   0  0.454479
14  14   6  0.284229

In [48]:
data_df.head()

A   B         C
0  0  13  0.247145
1  1  10  0.890317
2  2   1  0.635175
3  3  13  0.360963
4  4   9  0.803401

In [57]:
data_df.shape

(15, 3)

In [58]:
data_df[1:3]

A   B         C
1  1  10  0.890317
2  2   1  0.635175

In [59]:
data_df.loc[1]

A     1.000000
B    10.000000
C     0.890317
Name: 1, dtype: float64

In [60]:
data_df.loc[1]['C']

0.8903167322083826

In [61]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  13  0.247145  False
1    1  10  0.890317  False
2    2   1  0.635175  False
3    3  13  0.360963  False
4    4   9  0.803401  False
5    5  10  0.371818   True
6    6   2  0.985415   True
7    7  14  0.758669   True
8    8   2  0.807335   True
9    9   7  0.882133   True
10  10   7  0.255349   True
11  11  11  0.758977   True
12  12   3  0.294407   True
13  13   0  0.454479   True
14  14   6  0.284229   True

In [53]:
data_df.drop('D', axis=1, inplace=True)

In [54]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14   6  0.284229
13  13   0  0.454479
12  12   3  0.294407
11  11  11  0.758977
10  10   7  0.255349
9    9   7  0.882133
8    8   2  0.807335
7    7  14  0.758669
6    6   2  0.985415
5    5  10  0.371818
4    4   9  0.803401
3    3  13  0.360963
2    2   1  0.635175
1    1  10  0.890317
0    0  13  0.247145